# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:
  # Pin the version of Python you want!
  - python=3.14
  # Warning: jupyter-ai is evolving rapily! consider specific pin
  - jupyter-ai>=3.1
  # For vscode (or rstudio) UIs in addition to jupyterlab
  # https://docs.2i2c.org/admin/environment/alternative-interfaces/#vs-code-code-server
  - jupyter-server-proxy
  # VSCode
  # https://docs.2i2c.org/admin/environment/code-server
  - jupyter-vscode-proxy
  - code-server
  # SSH access
  # https://docs.2i2c.org/admin/environment/ssh-access/
  - jupyter-sshd-proxy
  # Event or domain-specific packages
  - geopandas>=1
  - xarray
  - pip
  - pip:
    # JupyterNaut in rapid flux https://github.com/jupyterlab/jupyter-ai/issues/1618
    - jupyter-ai-jupyternaut==0.1.0b1
    - jupyterhub-usage-quotas
